### ISSUE TITLE
Infinite boot loop during Sonoma installation

### ISSUE THREAD

**Issue by jackhu9527** [HJebbour/ThinkPad-X1C8-Hackintosh#7]
So I have an X1 Carbon Gen 8 which is very close to the one you have in terms of hardware specification:
Model 20U9
CPU: Intel i7-10610U
RAM: 16GB
SSD: 512GB
Screen: 2560x1440
Wi-fi & Bluetooth: Intel AX201

The UEFI settings were adjusted according to your guide.(BIOS Version: N2WET45W 1.35)

At the moment, I simply copied your EFI folder to the EFI partition of my Sonoma installation USB disk, and for an unknown reason I get infinite boot loop at the first loading screen. I would appreciate it if you could suggest how to identify the cause or how to fix this, thanks and I look forward to your feedback.

**Comment by HJebbour** [comment]
The Thunderbolt & Display UEFI settings are not relevant for macOS to run on the laptop, I just shared my exact settings, and the issue you have is normal but both settings should work and it doesn't have anything with the boot loop. Could you share the verbose boot?

**Comment by jackhu9527** [comment]
Thanks for your swift response and well noted. 
I switched to the OpenCore 1.0.0 DEBUG version, and please find attached the most recent log. [opencore-2024-06-23-225236.txt](https://github.com/user-attachments/files/15945114/opencore-2024-06-23-225236.txt)

**Comment by HJebbour** [comment]
Did you generate your serial number using GenSMBIOS?

**Comment by jackhu9527** [comment]
Hi, I realized that all the issues that I have come across may be caused by the Hynix SSD that came with my X1 Carbon. As such I replaced it with a WD SN730 SSD and now everything works like a charm! Thanks for your kind support and I really appreciate it.
